const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';
const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
const DELETE_PRODUCT = 'DELETE_PRODUCT';
const TOGGLE_SORT_PROPERTY = 'TOGGLE_SORT_PROPERTY'
const SEARCH_TERM_VALUE = 'SEARCH_TERM_VALUE'

export {
  FETCH_PRODUCTS_REQUEST,
  FETCH_PRODUCTS_SUCCESS,
  FETCH_PRODUCTS_FAIL,
  UPDATE_PRODUCT,
  DELETE_PRODUCT,
  TOGGLE_SORT_PROPERTY,
  SEARCH_TERM_VALUE
};