const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST'
const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL'

export {
	FETCH_PRODUCTS_REQUEST,
	FETCH_PRODUCTS_SUCCESS,
	FETCH_PRODUCTS_FAIL
}